CREATE TABLE IF NOT EXISTS accounts (
id INTEGER PRIMARY KEY,
username VARCHAR (127) NOT NULL
UNIQUE,
password VARCHAR (512) NOT NULL,
balance DOUBLE (14, 2) NOT NULL,
firstname VARCHAR (255) NOT NULL,
lastname VARCHAR (255) NOT NULL,
city VARCHAR (255) NOT NULL
);